version: '3'
services:
  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - todo-list-network
    environment:
      - POSTGRES_DB=todo-list-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    restart: unless-stopped
  be:
    build: .
    ports:
      - "8080:8080"
    networks:
      - todo-list-network
    environment:
      - POSTGRES_URL=postgres:5432
      - POSTGRES_DB=todo-list-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    env_file:
      - spring-variables.env
    depends_on:
      - postgres
    links:
      - "postgres:db"
    restart: unless-stopped

networks:
  todo-list-network:
    driver: bridge
