cognito:
  urlRoot: # your custom domain
  clientId: # your clientID
  clientSecret: # your clientSecret
  redirectUri: # your callback URI
  region: # your region
  poolId: # your PoolId
  issuer: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.poolId}
  keyStorePath: ${cognito.issuer}/.well-known/jwks.json

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
