cognito:
  domain: ${COGNITO_DOMAIN:}
  clientId: ${COGNITO_CLIENT_ID:}
  clientSecret: ${COGNITO_CLIENT_SECRET:}
  redirectUri: http://localhost:8080/auth/token
  region: ${AWS_REGION:}
  poolId: ${COGNITO_POOL_ID:}
  issuer: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.poolId}
  keyStorePath: ${cognito.issuer}/.well-known/jwks.json
  urlRoot: https://${cognito.domain}.auth.${cognito.region}.amazoncognito.com

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DB:test}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
