-- liquibase formatted sql
-- changeset author:kcymerys

CREATE TABLE TASK
(
    ID          BIGINT DEFAULT NEXTVAL('HIBERNATE_SEQUENCE'),
    TITLE       VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1024),
    STATUS      INTEGER      NOT NULL,
    USER_ID     BIGINT       NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES COGNITO_USER (ID) ON DELETE CASCADE
);
